// const architectEngineersData = [
//   {
//     id: 1,
//     name: "Mr. A. Balasubramani",
//     designation: "President",
//     company: "Sri Bhava Planners & Engineer",
//     regNo: "TN/L/08/1239",
//     panel: "Architect & Engineers Panel",
//     location: "Chennai",
//     email: "abala2312@gmail.com",
//     phone: "9840084810",
//   },
//   {
//     id: 2,
//     name: "Mr. U. Sampath",
//     designation: "Secretary General",
//     company: "SR Construction & Promoters",
//     regNo: "TN/L/01/1228",
//     panel: "Architect & Engineers Panel",
//     location: "Thanjavur",
//     email: "sampath1469@gmail.com",
//     phone: "9952804884",
//   },
//   {
//     id: 3,
//     name: "Mr. A. Ramesh Kumar",
//     designation: "Secretary – Operation",
//     company: "Sky Homes",
//     regNo: "TN/L/02/1365",
//     panel: "Architect & Engineers Panel",
//     location: "Chengelpett",
//     email: "skyhomes.tnj@gmail.com",
//     phone: "9843295562",
//   },
//   {
//     id: 4,
//     name: "Mr. R. Harikrishnan",
//     designation: "Secretary – Admin",
//     company: "High Value Housing & Developers Pvt. Ltd",
//     regNo: "TN/L/06/1273",
//     panel: "Architect & Engineers Panel",
//     location: "Chengelpett",
//     email: "hariagbc@gmail.com",
//     phone: "7010557210",
//   },
//   {
//     id: 5,
//     name: "Mr. C. Ramkanth",
//     designation: "Secretary – Development",
//     company: "TSR Builders",
//     regNo: "TN/L/01/1330",
//     panel: "Architect & Engineers Panel",
//     location: "Thiruvannamalai",
//     email: "tsrbuilder@gmail.com",
//     phone: "9894888777",
//   },
//   {
//     id: 6,
//     name: "Mr. P. Suresh Kumar",
//     designation: "Treasurer",
//     company: "SRS CADD",
//     regNo: "TN/P/06/034",
//     panel: "Architect & Engineers Panel",
//     location: "Villupuram",
//     email: "periyansureshkumar@gmail.com",
//     phone: "9944755153",
//   },
//   {
//     id: 7,
//     name: "Mr. K. Sasikumar",
//     designation: "Vice President",
//     company: "GVR Golden Promoters",
//     regNo: "TN/P/01/112",
//     panel: "Architect & Engineers Panel",
//     location: "Thanjavur",
//     email: "ss.associates.sasi@gmail.com",
//     phone: "9443128789",
//   },
//   {
//     id: 8,
//     name: "Mr. K. Yokanathan",
//     designation: "Vice President",
//     company: "Yoka Infra",
//     regNo: "TN/P/02/083",
//     panel: "Architect & Engineers Panel",
//     location: "Chennai",
//     email: "yokanathan@rediffmail.com",
//     phone: "9962046699",
//   },
//   {
//     id: 9,
//     name: "Mr. R. Balaji",
//     designation: "Organising Secretary",
//     company: "Harini Builders",
//     regNo: "TN/P/02/009",
//     panel: "Architect & Engineers Panel",
//     location: "Chennai",
//     email: "balajir9697@gmail.com",
//     phone: "7358669996",
//   },
//   {
//     id: 10,
//     name: "Mr. S. Bala Vasanth",
//     designation: "Organising Secretary",
//     company: "S R Construction",
//     regNo: "TN/P/02/1482",
//     panel: "Architect & Engineers Panel",
//     location: "Thanjavur",
//     email: "balavasanth4884@gmail.com",
//     phone: "8015804224",
//   },
//   {
//     id: 11,
//     name: "Mr. A. Shafiullaha",
//     designation: "Co-Ordinator",
//     company: "3 Line CADD",
//     regNo: "TN/P/06/064",
//     panel: "Architect & Engineers Panel",
//     location: "Villupuram",
//     email: "shaficadd@gmail.com",
//     phone: "9677743344",
//   },
//   {
//     id: 12,
//     name: "Mr. R. Venkatesan",
//     designation: "Co-Ordinator",
//     company: "Asian Builders",
//     regNo: "TN/P/02/084",
//     panel: "Architect & Engineers Panel",
//     location: "Ranipet",
//     email: "venkatesan3119@gmail.com",
//     phone: "9677993119",
//   },
//   {
//     id: 13,
//     name: "Mr. Mylai Murali",
//     designation: "Joint Secretary",
//     company: "Future Star Consulting Services",
//     regNo: "TN/L/11/1230",
//     panel: "Architect & Engineers Panel",
//     location: "Chennai",
//     email: "59futurestar@gmail.com",
//     phone: "9677101625",
//   },
//   {
//     id: 14,
//     name: "Mr. S. Sudharsan",
//     designation: "Joint Secretary",
//     company: "Sri Balaji Real Estates",
//     regNo: "TN/L/01/1480",
//     panel: "Architect & Engineers Panel",
//     location: "Thanjavur",
//     email: "sudharsansowmi@outlook.com",
//     phone: "9363032271",
//   },
//   {
//     id: 15,
//     name: "Mr. S. Venkatesan",
//     designation: "Deputy Secretary",
//     company: "4th Dimension",
//     regNo: "TN/P/08/036",
//     panel: "Architect & Engineers Panel",
//     location: "Villupuram",
//     email: "venkatvivil274@gmail.com",
//     phone: "9790682895",
//   },
//   {
//     id: 16,
//     name: "Mr. E. Paulanna",
//     designation: "Executive Committee Member",
//     company: "Prince Construction & Consultant",
//     regNo: "TN/L/01/1279",
//     panel: "Architect & Engineers Panel",
//     location: "Thirunelveli",
//     email: "paulanna.er1@gmail.com",
//     phone: "9443414461",
//   },
//   {
//     id: 17,
//     name: "Mr. A. Soundarajan",
//     designation: "Executive Committee Member",
//     company: "G.V. Visual Creation",
//     regNo: "TN/L/06/1286",
//     panel: "Architect & Engineers Panel",
//     location: "Namakkal",
//     email: "soundarcivil1024@gmail.com",
//     phone: "9578270663",
//   },
//   {
//     id: 18,
//     name: "Ms. S. S. Thejaswani",
//     designation: "Executive Committee Member",
//     company: "Thejas Associates",
//     regNo: "TN/L/03/1483",
//     panel: "Architect & Engineers Panel",
//     location: "Coimbatore",
//     email: "thejswiniss2002@gmail.com",
//     phone: "9025235608",
//   },
// ];

// export default architectEngineersData;



// const architectData = [
//   {
//     id: 1,
//     name: "Mr. A. Balasubramani",
//     designation: "President",
//     company: "Sri Bhava Planners & Engineer",
//     regNo: "TN/L/08/1239",
//     panel: "Architect & Engineers Panel",
//     location: "Chennai",
//     email: "abala2312@gmail.com",
//     phone: "9840084810",
//   },
//   {
//     id: 2,
//     name: "Mr. U. Sampath",
//     designation: "Secretary General",
//     company: "SR Construction & Promoters",
//     regNo: "TN/L/01/1228",
//     panel: "Architect & Engineers Panel",
//     location: "Thanjavur",
//     email: "sampath1469@gmail.com",
//     phone: "9952804884",
//   },
//   {
//     id: 3,
//     name: "Mr. A. Ramesh Kumar",
//     designation: "Secretary – Operation",
//     company: "Sky Homes",
//     regNo: "TN/L/02/1365",
//     panel: "Architect & Engineers Panel",
//     location: "Chengelpett",
//     email: "skyhomes.tnj@gmail.com",
//     phone: "9843295562",
//   },
//   {
//     id: 4,
//     name: "Mr. R. Harikrishnan",
//     designation: "Secretary – Admin",
//     company: "High Value Housing & Developers Pvt. Ltd",
//     regNo: "TN/L/06/1273",
//     panel: "Architect & Engineers Panel",
//     location: "Chengelpett",
//     email: "hariagbc@gmail.com",
//     phone: "7010557210",
//   },
//   {
//     id: 5,
//     name: "Mr. C. Ramkanth",
//     designation: "Secretary – Development",
//     company: "TSR Builders",
//     regNo: "TN/L/01/1330",
//     panel: "Architect & Engineers Panel",
//     location: "Thiruvannamalai",
//     email: "tsrbuilder@gmail.com",
//     phone: "9894888777",
//   },
//   {
//     id: 6,
//     name: "Mr. P. Suresh Kumar",
//     designation: "Treasurer",
//     company: "SRS CADD",
//     regNo: "TN/P/06/034",
//     panel: "Architect & Engineers Panel",
//     location: "Villupuram",
//     email: "periyansureshkumar@gmail.com",
//     phone: "9944755153",
//   },
//   {
//     id: 7,
//     name: "Mr. K. Sasikumar",
//     designation: "Vice President",
//     company: "GVR Golden Promoters",
//     regNo: "TN/P/01/112",
//     panel: "Architect & Engineers Panel",
//     location: "Thanjavur",
//     email: "ss.associates.sasi@gmail.com",
//     phone: "9443128789",
//   },
//   {
//     id: 8,
//     name: "Mr. K. Yokanathan",
//     designation: "Vice President",
//     company: "Yoka Infra",
//     regNo: "TN/P/02/083",
//     panel: "Architect & Engineers Panel",
//     location: "Chennai",
//     email: "yokanathan@rediffmail.com",
//     phone: "9962046699",
//   },
//   {
//     id: 9,
//     name: "Mr. R. Balaji",
//     designation: "Organising Secretary",
//     company: "Harini Builders",
//     regNo: "TN/P/02/009",
//     panel: "Architect & Engineers Panel",
//     location: "Chennai",
//     email: "balajir9697@gmail.com",
//     phone: "7358669996",
//   },
//   {
//     id: 10,
//     name: "Mr. S. Bala Vasanth",
//     designation: "Organising Secretary",
//     company: "S R Construction",
//     regNo: "TN/P/02/1482",
//     panel: "Architect & Engineers Panel",
//     location: "Thanjavur",
//     email: "balavasanth4884@gmail.com",
//     phone: "8015804224",
//   },
//   {
//     id: 11,
//     name: "Mr. A. Shafiullaha",
//     designation: "Co-Ordinator",
//     company: "3 Line CADD",
//     regNo: "TN/P/06/064",
//     panel: "Architect & Engineers Panel",
//     location: "Villupuram",
//     email: "shaficadd@gmail.com",
//     phone: "9677743344",
//   },
//   {
//     id: 12,
//     name: "Mr. R. Venkatesan",
//     designation: "Co-Ordinator",
//     company: "Asian Builders",
//     regNo: "TN/P/02/084",
//     panel: "Architect & Engineers Panel",
//     location: "Ranipet",
//     email: "venkatesan3119@gmail.com",
//     phone: "9677993119",
//   },
//   {
//     id: 13,
//     name: "Mr. Mylai Murali",
//     designation: "Joint Secretary",
//     company: "Future Star Consulting Services",
//     regNo: "TN/L/11/1230",
//     panel: "Architect & Engineers Panel",
//     location: "Chennai",
//     email: "59futurestar@gmail.com",
//     phone: "9677101625",
//   },
//   {
//     id: 14,
//     name: "Mr. S. Sudharsan",
//     designation: "Joint Secretary",
//     company: "Sri Balaji Real Estates",
//     regNo: "TN/L/01/1480",
//     panel: "Architect & Engineers Panel",
//     location: "Thanjavur",
//     email: "sudharsansowmi@outlook.com",
//     phone: "9363032271",
//   },
//   {
//     id: 15,
//     name: "Mr. S. Venkatesan",
//     designation: "Deputy Secretary",
//     company: "4th Dimension",
//     regNo: "TN/P/08/036",
//     panel: "Architect & Engineers Panel",
//     location: "Villupuram",
//     email: "venkatvivil274@gmail.com",
//     phone: "9790682895",
//   },
//   {
//     id: 16,
//     name: "Mr. E. Paulanna",
//     designation: "Executive Committee Member",
//     company: "Prince Construction & Consultant",
//     regNo: "TN/L/01/1279",
//     panel: "Architect & Engineers Panel",
//     location: "Thirunelveli",
//     email: "paulanna.er1@gmail.com",
//     phone: "9443414461",
//   },
//   {
//     id: 17,
//     name: "Mr. A. Soundarajan",
//     designation: "Executive Committee Member",
//     company: "G.V. Visual Creation",
//     regNo: "TN/L/06/1286",
//     panel: "Architect & Engineers Panel",
//     location: "Namakkal",
//     email: "soundarcivil1024@gmail.com",
//     phone: "9578270663",
//   },
//   {
//     id: 18,
//     name: "Ms. S. S. Thejaswani",
//     designation: "Executive Committee Member",
//     company: "Thejas Associates",
//     regNo: "TN/L/03/1483",
//     panel: "Architect & Engineers Panel",
//     location: "Coimbatore",
//     email: "thejswiniss2002@gmail.com",
//     phone: "9025235608",
//   },
// ];

// export default architectData;



const architectData = [
  {
    id: 1,
    name: "Mr. A. Balasubramani",
    designation: "President",
    company: "Sri Bhava Planners & Engineer",
    regNo: "TN/L/08/1239",
    panel: "Architect & Engineers Panel",
    location: "Chennai",
    email: "abala2312@gmail.com",
    phone: "9840084810",
    website: "https://sribhavaplanners.com/",
  },
  {
    id: 2,
    name: "Mr. U. Sampath",
    designation: "Secretary General",
    company: "SR Construction & Promoters",
    regNo: "TN/L/01/1228",
    panel: "Architect & Engineers Panel",
    location: "Thanjavur",
    email: "sampath1469@gmail.com",
    phone: "9952804884",
    website: "https://srbuilderstn.com/",
  },
  {
    id: 3,
    name: "Mr. A. Ramesh Kumar",
    designation: "Secretary – Operation",
    company: "Sky Homes",
    regNo: "TN/L/02/1365",
    panel: "Architect & Engineers Panel",
    location: "Chengalpattu",
    email: "skyhomes.tnj@gmail.com",
    phone: "9843295562",
    website: "https://www.theskyhomes.com/",
  },
  {
    id: 4,
    name: "Mr. R. Harikrishnan",
    designation: "Secretary – Admin",
    company: "High Value Housing & Developers Pvt. Ltd",
    regNo: "TN/L/06/1273",
    panel: "Architect & Engineers Panel",
    location: "Chengalpattu",
    email: "hariagbc@gmail.com",
    phone: "7010557210",
  },
  {
    id: 5,
    name: "Mr. C. Ramkanth",
    designation: "Secretary – Development",
    company: "TSR Builders",
    regNo: "TN/L/01/1330",
    panel: "Architect & Engineers Panel",
    location: "Thiruvannamalai",
    email: "tsrbuilder@gmail.com",
    phone: "9894888777",
  },
  {
    id: 6,
    name: "Mr. P. Suresh Kumar",
    designation: "Treasurer",
    company: "SRS CADD",
    regNo: "TN/P/06/034",
    panel: "Architect & Engineers Panel",
    location: "Villupuram",
    email: "periyansureshkumar@gmail.com",
    phone: "9944755153",
  },
  {
    id: 7,
    name: "Mr. K. Sasikumar",
    designation: "Vice President",
    company: "GVR Golden Promoters",
    regNo: "TN/P/01/112",
    panel: "Architect & Engineers Panel",
    location: "Thanjavur",
    email: "ss.associates.sasi@gmail.com",
    phone: "9443128789",
  },
  {
    id: 8,
    name: "Mr. K. Yokanathan",
    designation: "Vice President",
    company: "Yoka Infra",
    regNo: "TN/P/02/083",
    panel: "Architect & Engineers Panel",
    location: "Chennai",
    email: "yokanathan@rediffmail.com",
    phone: "9962046699",
    website: "https://www.yoginfra.com/",
  },
  {
    id: 9,
    name: "Mr. R. Balaji",
    designation: "Organising Secretary",
    company: "Harini Builders",
    regNo: "TN/P/02/009",
    panel: "Architect & Engineers Panel",
    location: "Chennai",
    email: "balajir9697@gmail.com",
    phone: "7358669996",
    website: "http://www.harinibuilders.com/",
  },
  {
    id: 10,
    name: "Mr. S. Bala Vasanth",
    designation: "Organising Secretary",
    company: "S R Construction",
    regNo: "TN/P/02/1482",
    panel: "Architect & Engineers Panel",
    location: "Thanjavur",
    email: "balavasanth4884@gmail.com",
    phone: "8015804224",
  },
  {
    id: 11,
    name: "Mr. A. Shafiullaha",
    designation: "Co-Ordinator",
    company: "3 Line CADD",
    regNo: "TN/P/06/064",
    panel: "Architect & Engineers Panel",
    location: "Villupuram",
    email: "shaficadd@gmail.com",
    phone: "9677743344",
  },
  {
    id: 12,
    name: "Mr. R. Venkatesan",
    designation: "Co-Ordinator",
    company: "Asian Builders",
    regNo: "TN/P/02/084",
    panel: "Architect & Engineers Panel",
    location: "Ranipet",
    email: "venkatesan3119@gmail.com",
    phone: "9677993119",
    website: "https://www.asiabuildersindia.com/",
  },
  {
    id: 13,
    name: "Mr. Mylai Murali",
    designation: "Joint Secretary",
    company: "Future Star Consulting Services",
    regNo: "TN/L/11/1230",
    panel: "Architect & Engineers Panel",
    location: "Chennai",
    email: "59futurestar@gmail.com",
    phone: "9677101625",
  },
  {
    id: 14,
    name: "Mr. S. Sudharsan",
    designation: "Joint Secretary",
    company: "Sri Balaji Real Estates",
    regNo: "TN/L/01/1480",
    panel: "Architect & Engineers Panel",
    location: "Thanjavur",
    email: "sudharsansowmi@outlook.com",
    phone: "9363032271",
    website: "https://sbrrealestate.com/",
  },
  {
    id: 15,
    name: "Mr. S. Venkatesan",
    designation: "Deputy Secretary",
    company: "4th Dimension",
    regNo: "TN/P/08/036",
    panel: "Architect & Engineers Panel",
    location: "Villupuram",
    email: "venkatvivil274@gmail.com",
    phone: "9790682895",
    website: "https://4thd.in/",
  },
  {
    id: 16,
    name: "Mr. E. Paulanna",
    designation: "Executive Committee Member",
    company: "Prince Construction & Consultant",
    regNo: "TN/L/01/1279",
    panel: "Architect & Engineers Panel",
    location: "Thirunelveli",
    email: "paulanna.er1@gmail.com",
    phone: "9443414461",
  },
  {
    id: 17,
    name: "Mr. A. Soundarajan",
    designation: "Executive Committee Member",
    company: "G.V. Visual Creation",
    regNo: "TN/L/06/1286",
    panel: "Architect & Engineers Panel",
    location: "Namakkal",
    email: "soundarcivil1024@gmail.com",
    phone: "9578270663",
  },
  {
    id: 18,
    name: "Ms. S. S. Thejaswani",
    designation: "Executive Committee Member",
    company: "Thejas Associates",
    regNo: "TN/L/03/1483",
    panel: "Architect & Engineers Panel",
    location: "Coimbatore",
    email: "thejswiniss2002@gmail.com",
    phone: "9025235608",
    website: "https://thejas.org.in/contact",
  },
];

export default architectData;
