// const buildersData = [
//   {
//     id: 1,
//     name: "Mr. R. Kannan Nadhakumar",
//     designation: "President",
//     company: "Sathyam Homes Pvt. Ltd",
//     registrationNo: "TN/P/02/020",
//     panel: "Builders & Promoters Panel",
//     city: "Chengelpett",
//     email: "md@sathyamhomes.co.in",
//     phone: "9445008081",
//   },
//   {
//     id: 2,
//     name: "Mr. A. Kamalahasan",
//     designation: "Secretary General",
//     company: "Keerthi Promoters",
//     registrationNo: "TN/L/02/1087",
//     panel: "Builders & Promoters Panel",
//     city: "Chennai",
//     email: "keerthipromoters@gmail.com",
//     phone: "9710035667",
//   },
//   {
//     id: 3,
//     name: "Mr. A. Saminathan",
//     designation: "Secretary – Operation",
//     company: "Nithiya Homes",
//     registrationNo: "TN/P/01/056",
//     panel: "Builders & Promoters Panel",
//     city: "Chennai",
//     email: "nithyahomes@gmail.com",
//     phone: "9566227474",
//   },
//   {
//     id: 4,
//     name: "Mr. M. Karthic",
//     designation: "Secretary – Admin",
//     company: "Aadhav Realty",
//     registrationNo: "TN/L/02/1128",
//     panel: "Builders & Promoters Panel",
//     city: "Virudhunagar",
//     email: "karrthicrealty@gmail.com",
//     phone: "9003439595",
//   },
//   {
//     id: 5,
//     name: "Mr. K. Vijaya Bharathi",
//     designation: "Secretary – Development",
//     company: "Rajan Grove (P) Ltd",
//     registrationNo: "TN/L/01/1130",
//     panel: "Builders & Promoters Panel",
//     city: "Madurai",
//     email: "kvijayabharathi@yahoo.com",
//     phone: "9962576305",
//   },
//   {
//     id: 6,
//     name: "Mr. P. Ganesh Kumar",
//     designation: "Treasurer",
//     company: "Gain Homes Land Developers",
//     registrationNo: "TN/L/01/1035",
//     panel: "Builders & Promoters Panel",
//     city: "Coimbatore",
//     email: "parrealtors@gmail.com",
//     phone: "9944782987",
//   },
//   {
//     id: 7,
//     name: "Mr. S. Ramanathan",
//     designation: "Executive Committee Chairman",
//     company: "Real Value Land Promoters & Builder Pvt Ltd",
//     registrationNo: "TN/P/02/061",
//     panel: "Builders & Promoters Panel",
//     city: "Coimbatore",
//     email: "realvaluelandpromoterscbe@gmail.com",
//     phone: "7871323338",
//   },
//   {
//     id: 8,
//     name: "Mr. J. Sudhakar",
//     designation: "Advisory Board Chairman",
//     company: "Sathyam Properties",
//     registrationNo: "TN/P/01/023",
//     panel: "Builders & Promoters Panel",
//     city: "Chengelpett",
//     email: "devisudha.ds@gmail.com",
//     phone: "9566102354",
//   },
//   {
//     id: 9,
//     name: "Mr. S. Sureshkumar",
//     designation: "Vice President",
//     company: "SKM Promoters",
//     registrationNo: "TN/P/02/042",
//     panel: "Builders & Promoters Panel",
//     city: "Coimbatore",
//     email: "info@skmpromotersl.com",
//     phone: "9842011575",
//   },
//   {
//     id: 10,
//     name: "Mr. P. Nagarajan",
//     designation: "Vice President",
//     company: "Agam Infra & Realty",
//     registrationNo: "TN/L/01/1205",
//     panel: "Builders & Promoters Panel",
//     city: "Thiruvannamalai",
//     email: "nagarajanptvm@gmail.com",
//     phone: "9443338589",
//   }
// ];

// export default buildersData;


const buildersData = [
  {
    id: 1,
    name: "Mr. R. Kannan Nadhakumar",
    designation: "President",
    company: "Sathyam Homes Pvt. Ltd",
    registrationNo: "TN/P/02/020",
    panel: "Builders & Promoters Panel",
    city: "Chengelpett",
    email: "md@sathyamhomes.co.in",
    phone: "9445008081",
    website: "https://sathyamhomes.co.in/"
  },
  {
    id: 2,
    name: "Mr. A. Kamalahasan",
    designation: "Secretary General",
    company: "Keerthi Promoters",
    registrationNo: "TN/L/02/1087",
    panel: "Builders & Promoters Panel",
    city: "Chennai",
    email: "keerthipromoters@gmail.com",
    phone: "9710035667",
    website: "http://keerthipromoters.com"
  },
  {
    id: 3,
    name: "Mr. A. Saminathan",
    designation: "Secretary – Operation",
    company: "Nithiya Homes",
    registrationNo: "TN/P/01/056",
    panel: "Builders & Promoters Panel",
    city: "Chennai",
    email: "nithyahomes@gmail.com",
    phone: "9566227474",
    website: ""
  },
  {
    id: 4,
    name: "Mr. M. Karthic",
    designation: "Secretary – Admin",
    company: "Aadhav Realty",
    registrationNo: "TN/L/02/1128",
    panel: "Builders & Promoters Panel",
    city: "Virudhunagar",
    email: "karrthicrealty@gmail.com",
    phone: "9003439595",
    website: ""
  },
  {
    id: 5,
    name: "Mr. K. Vijaya Bharathi",
    designation: "Secretary – Development",
    company: "Rajan Grove (P) Ltd",
    registrationNo: "TN/L/01/1130",
    panel: "Builders & Promoters Panel",
    city: "Madurai",
    email: "kvijayabharathi@yahoo.com",
    phone: "9962576305",
    website: ""
  },
  {
    id: 6,
    name: "Mr. P. Ganesh Kumar",
    designation: "Treasurer",
    company: "Gain Homes Land Developers",
    registrationNo: "TN/L/01/1035",
    panel: "Builders & Promoters Panel",
    city: "Coimbatore",
    email: "parrealtors@gmail.com",
    phone: "9944782987",
    website: ""
  },
  {
    id: 7,
    name: "Mr. S. Ramanathan",
    designation: "Executive Committee Chairman",
    company: "Real Value Land Promoters & Builder Pvt Ltd",
    registrationNo: "TN/P/02/061",
    panel: "Builders & Promoters Panel",
    city: "Coimbatore",
    email: "realvaluelandpromoterscbe@gmail.com",
    phone: "7871323338",
    website: "https://www.realvaluepromoters.com/"
  },
  {
    id: 8,
    name: "Mr. J. Sudhakar",
    designation: "Advisory Board Chairman",
    company: "Sathyam Properties",
    registrationNo: "TN/P/01/023",
    panel: "Builders & Promoters Panel",
    city: "Chengelpett",
    email: "devisudha.ds@gmail.com",
    phone: "9566102354",
    website: "https://sathyamproperties.in/"
  },
  {
    id: 9,
    name: "Mr. S. Sureshkumar",
    designation: "Vice President",
    company: "SKM Promoters",
    registrationNo: "TN/P/02/042",
    panel: "Builders & Promoters Panel",
    city: "Coimbatore",
    email: "info@skmpromotersl.com",
    phone: "9842011575",
    website: "https://www.skmpromoters.com/"
  },
  {
    id: 10,
    name: "Mr. P. Nagarajan",
    designation: "Vice President",
    company: "Agam Infra & Realty",
    registrationNo: "TN/L/01/1205",
    panel: "Builders & Promoters Panel",
    city: "Thiruvannamalai",
    email: "nagarajanptvm@gmail.com",
    phone: "9443338589",
    website: ""
  },
  {
    id: 11,
    name: "Mr. V. Muralidharan",
    designation: "Organising Secretary",
    company: "Metro City Developers",
    registrationNo: "TN/P/06/068",
    panel: "Builders & Promoters Panel",
    city: "Coimbatore",
    email: "metrocitycoimbatore@gmail.com",
    phone: "9994399923",
    website: "https://metrocitydevelopers.com/"
  },
  {
    id: 12,
    name: "Mr. G. Thaasan",
    designation: "Organising Secretary",
    company: "Veppur Reality Group",
    registrationNo: "TN/P/01/050",
    panel: "Builders & Promoters Panel",
    city: "Cuddalore",
    email: "shakthithaasan6@gmail.com",
    phone: "9443292493",
    website: ""
  },
  {
    id: 13,
    name: "Mr. T. Baskaran",
    designation: "Co-Ordinator",
    company: "Kamatchi Foundation",
    registrationNo: "TN/L/02/1135",
    panel: "Builders & Promoters Panel",
    city: "Chennai",
    email: "kamatchifoundation@gmail.com",
    phone: "9840943334",
    website: ""
  },
  {
    id: 14,
    name: "Mr. Jagadeesh Dhandapani",
    designation: "Co-Ordinator",
    company: "Annai Sri Mookambika Real Estate & Builders",
    registrationNo: "TN/L/01/1389",
    panel: "Builders & Promoters Panel",
    city: "Thiruvannamalai",
    email: "jagadesh.tvm@gmail.com",
    phone: "9952546447",
    website: ""
  },
  {
    id: 15,
    name: "Mr. R. Vamanan",
    designation: "Joint Secretary",
    company: "Vamanan Estates",
    registrationNo: "TN/P/01/110",
    panel: "Builders & Promoters Panel",
    city: "Chengelpett",
    email: "vamananestates@gmail.com",
    phone: "9841177703",
    website: "https://vamananestates.com/"
  },
  {
    id: 16,
    name: "Mr. G. Tilok Chand Jain",
    designation: "Joint Secretary",
    company: "L&T Developers",
    registrationNo: "TN/P/01/053",
    panel: "Builders & Promoters Panel",
    city: "Chennai",
    email: "tbhansali26@gmail.com",
    phone: "9840110179",
    website: ""
  },
  {
    id: 17,
    name: "Mr. H. Lalith Kumar Jain",
    designation: "Deputy Secretary",
    company: "L&T Developers",
    registrationNo: "TN/P/01/053",
    panel: "Builders & Promoters Panel",
    city: "Chennai",
    email: "lgnn1079@yahoo.in",
    phone: "9840127583",
    website: ""
  },
  {
    id: 18,
    name: "Mr. K. R. Perumal",
    designation: "Deputy Secretary",
    company: "K R P Builders & Promoters",
    registrationNo: "TN/L/02/1219",
    panel: "Builders & Promoters Panel",
    city: "Chennai",
    email: "krpagency@gmail.com",
    phone: "9361616449",
    website: ""
  },
  {
    id: 19,
    name: "Mr. Faisal Ahamed Ali",
    designation: "Deputy Treasurer",
    company: "MSM Promoters",
    registrationNo: "TN/L/01/1294",
    panel: "Builders & Promoters Panel",
    city: "Thanjavur",
    email: "faisalaali888@gmail.com",
    phone: "9566698307",
    website: ""
  },
  {
    id: 20,
    name: "Mr. Deen Mohamed",
    designation: "Executive Committee Vice Chairman",
    company: "Marina Promoter",
    registrationNo: "TN/P/01/062",
    panel: "Builders & Promoters Panel",
    city: "Thanjavur",
    email: "deenmohamed1982@gmail.com",
    phone: "9486739226",
    website: ""
  },
  {
    id: 21,
    name: "Mr. S. Shriram",
    designation: "Advisory Board Vice Chairman",
    company: "Premier Real Estates",
    registrationNo: "TN/P/01/105",
    panel: "Builders & Promoters Panel",
    city: "Thanjavur",
    email: "sriram@premiertravels.co.in",
    phone: "9443317484",
    website: "https://premier-realestate.in/"
  },
  {
    id: 22,
    name: "Mr. R. D. Jayaprakash",
    designation: "Advisory Board Member",
    company: "R.D.P Construction",
    registrationNo: "TN/L/01/1360",
    panel: "Builders & Promoters Panel",
    city: "Thiruvannamalai",
    email: "rdprakash1977@gmail.com",
    phone: "9443103730",
    website: "https://rdpconstructiongroup.com/"
  },
  {
    id: 23,
    name: "Mr. S. K. Thilaivannan",
    designation: "Advisory Board Member",
    company: "CM Enterprises",
    registrationNo: "TN/L/02/1184",
    panel: "Builders & Promoters Panel",
    city: "Chennai",
    email: "thillaivanan.s.t@gmail.com",
    phone: "9790978200",
    website: "https://cmenterprises.com/cm-realestate/"
  },
  {
    id: 24,
    name: "Mr. S. K. Viji",
    designation: "Advisory Board Member",
    company: "SKR Real Estate",
    registrationNo: "TN/P/01/101",
    panel: "Builders & Promoters Panel",
    city: "Thanjavur",
    email: "",
    phone: "7373630083",
    website: "https://skrgroup.co/"
  },
  {
    id: 25,
    name: "Mr. D. Karthik",
    designation: "Advisory Board Member",
    company: "K P Developers",
    registrationNo: "TN/L/02/1115",
    panel: "Builders & Promoters Panel",
    city: "Chennai",
    email: "kartikdevan1982@gmail.com",
    phone: "9884879817",
    website: "https://kpdny.com/"
  },
  {
    id: 26,
    name: "Mr. K. Yuvaraj",
    designation: "Advisory Board Member",
    company: "Ajan Homes",
    registrationNo: "TN/L/02/1188",
    panel: "Builders & Promoters Panel",
    city: "Chennai",
    email: "ckyuuaraj4@gmail.com",
    phone: "9884037664",
    website: ""
  },
  {
    id: 27,
    name: "Mr. J. Gopalakrishnan",
    designation: "Executive Committee Member",
    company: "Sri Pathamaradha Enterprises",
    registrationNo: "TN/L/01/1248",
    panel: "Builders & Promoters Panel",
    city: "Vellore",
    email: "radhaenterprises71@gmail.com",
    phone: "9444147343",
    website: ""
  },
  {
    id: 28,
    name: "Mr. M. Jayaraj",
    designation: "Executive Committee Member",
    company: "S.M. Green Properties",
    registrationNo: "TN/L/02/1290",
    panel: "Builders & Promoters Panel",
    city: "Namakkal",
    email: "jai.87.raj@gmail.com",
    phone: "9976759995",
    website: ""
  },
  {
    id: 29,
    name: "Mr. S. Manickam",
    designation: "Executive Committee Member",
    company: "MGM Real Estate",
    registrationNo: "TN/P/01/057",
    panel: "Builders & Promoters Panel",
    city: "Coimbatore",
    email: "",
    phone: "9566474615",
    website: ""
  },
  {
    id: 30,
    name: "Mr. N. Velmurugan",
    designation: "Executive Committee Member",
    company: "SKM Promoters",
    registrationNo: "TN/L/02/1280",
    panel: "Builders & Promoters Panel",
    city: "Coimbatore",
    email: "vtharun05@gmail.com",
    phone: "9965736113",
    website: "https://www.skmpromoters.com/"
  },
  {
    id: 31,
    name: "Mr. Akshya Prakash",
    designation: "Executive Committee Member",
    company: "Akshya Promoters",
    registrationNo: "TN/L/01/1038",
    panel: "Builders & Promoters Panel",
    city: "Coimbatore",
    email: "akshyaspromoters@gmail.com",
    phone: "9500549293",
    website: "https://www.akshaya.com/index.html"
  },
  {
    id: 32,
    name: "Mr. K. Ramasamy",
    designation: "Executive Committee Member",
    company: "KRS Constructions",
    registrationNo: "TN/L/02/1119",
    panel: "Builders & Promoters Panel",
    city: "Chennai",
    email: "krsconstruction@yahoo.com",
    phone: "9042062627",
    website: ""
  },
  {
    id: 33,
    name: "Mr. G. Dhinakaran",
    designation: "Executive Committee Member",
    company: "Sri Sai Real Estate Foundation",
    registrationNo: "TN/L/02/1141",
    panel: "Builders & Promoters Panel",
    city: "Chennai",
    email: "srisaifoundation01@gmail.com",
    phone: "9629987185",
    website: "https://srisaiestates.com/"
  },
  {
    id: 34,
    name: "Mr. S. Saravanan",
    designation: "Executive Committee Member",
    company: "V T Constructions",
    registrationNo: "TN/L/02/1297",
    panel: "Builders & Promoters Panel",
    city: "Chennai",
    email: "stsaran3007@gmail.com",
    phone: "9840263403",
    website: "https://vtconstruction.org/"
  }
];

export default buildersData;
