export const lifetimeMembers = [
  {
    id: "PAT-001",
    img: "",
    name: "Ramesh Kumar",
    designation: "Managing Director",
    company: "RK Builders",
    location: "Chennai",
  },
  {
    id: "PAT-002",
    img: "",
    name: "Suresh Anand",
    designation: "Founder",
    company: "Anand Properties",
    location: "Coimbatore",
  },
  {
    id: "PAT-003",
    img: "",
    name: "Karthikeyan M",
    designation: "Director",
    company: "SK Developers",
    location: "Madurai",
  },
  {
    id: "PAT-004",
    img: "",
    name: "Arun Prakash",
    designation: "Chairman",
    company: "AP Realty",
    location: "Salem",
  },
  {
    id: "PAT-005",
    img: "",
    name: "Vignesh Raman",
    designation: "CEO",
    company: "VR Housing",
    location: "Trichy",
  },
  {
    id: "PAT-006",
    img: "",
    name: "Balaji Subramanian",
    designation: "Partner",
    company: "BS Constructions",
    location: "Erode",
  },
  {
    id: "PAT-007",
    img: "",
    name: "Naveen Krishnan",
    designation: "Managing Partner",
    company: "NK Infra",
    location: "Tirunelveli",
  },
  {
    id: "PAT-008",
    img: "",
    name: "Sathish Kumar",
    designation: "Director",
    company: "SK Realty",
    location: "Vellore",
  },
  {
    id: "PAT-009",
    img: "",
    name: "Prakash Iyer",
    designation: "Co-Founder",
    company: "PI Developers",
    location: "Thanjavur",
  },
  {
    id: "PAT-010",
    img: "",
    name: "Rajesh Mehta",
    designation: "Executive Director",
    company: "RM Estates",
    location: "Chennai",
  },
];
