const OwnersData = [
  {
    id: 1,
    name: "Mr. S. BALAJI",
    designation: "PRESIDENT",
    company: "SRI BALAJI REAL ESTATES",
    regNo: "TN/L/01/1259",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "THANJAVUR",
    email: "dgbalaji2122@gmail.com",
    phone: "9842432271",
    link: "/member/1",
  },
  {
    id: 2,
    name: "Mr. G. SIVAKUMAR",
    designation: "SECRETARY-GENERAL",
    company: "DSP GROUPS",
    regNo: "TN/L/01/1005",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "CHENGELPET",
    email: "sivaponmalar333@gmail.com",
    phone: "9952284084",
    link: "/member/2",
  },
  {
    id: 3,
    name: "Mr. K. CLEMENT ROSERIO",
    designation: "SECRETARY - OPERATION",
    company: "KCR DEVELOPERS & PROMOTERS",
    regNo: "TN/P/01/055",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "VILLUPURAM",
    email: "kcrbuilders&promoters@gmail.com",
    phone: "8778179369",
    link: "/member/3",
  },
  {
    id: 4,
    name: "Mr. S. MARAN",
    designation: "SECRETARY - ADMIN",
    company: "SRI CHAKRA PROMOTERS",
    regNo: "TN/P/01/079",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "THANJAVUR",
    email: "maransubbiya1975@gmail.com",
    phone: "9443030682",
    link: "/member/4",
  },
  {
    id: 5,
    name: "Mr. M. GANESAN",
    designation: "SECRETARY - DEVELOPMENT",
    company: "URBANOVA",
    regNo: "TN/P/02/069",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "SALEM",
    email: "ganeshglifecare@gmail.com",
    phone: "9842794980",
    link: "/member/5",
  },
  {
    id: 6,
    name: "Mr. C. V. RUNANA",
    designation: "TREASURER",
    company: "MADRAS CITY PROPERTIES.COM",
    regNo: "TN/L/01/1020",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "CHENNAI",
    email: "runana.cv@gmail.com",
    phone: "9003111668",
    link: "/member/6",
  },
  {
    id: 7,
    name: "Mr. R. KALAIVANAN",
    designation: "EXECUTIVE COMMITTEE - CHAIRMAN",
    company: "SATHYA ELITE PROPERTIES PVT. LTD",
    regNo: "TN/P/01/049",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "CHENNAI",
    email: "sathyapropertybazzar@gmail.com",
    phone: "9962619121",
    link: "/member/7",
  },
  {
    id: 8,
    name: "Mr. A. N. E. DAKSHINAMOORTHY",
    designation: "ADVISORY BOARD - CHAIRMAN",
    company: "C.M. ENTERPRISES",
    regNo: "TN/L/01/1209",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "CHENNAI",
    email: "grinderkaliappan@gmail.com",
    phone: "9841101085",
    link: "/member/8",
  },
  {
    id: 9,
    name: "Mr. R. C. THIYAGARAJAN",
    designation: "VICE-PRESIDENT",
    company: "R.R. REAL ESTATE",
    regNo: "TN/L/01/1178",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "COIMBATORE",
    email: "hrrgrand@gmail.com",
    phone: "9842279779",
    link: "/member/9",
  },
  {
    id: 10,
    name: "Mr. A. SELLA PERUMAL",
    designation: "VICE-PRESIDENT",
    company: "OM GANAPATHY CRANES & EARTH MOVERS",
    regNo: "TN/P/01/054",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "VILLUPURAM",
    email: "aksellaperumal@gmail.com",
    phone: "8778430088",
    link: "/member/10",
  },
  {
    id: 11,
    name: "Mrs. R. KANIMOZHI",
    designation: "ORGANISING SECRETARY",
    company: "MATHIRA ASSOCIATES & PROMOTERS",
    regNo: "TN/L/01/1238",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "THIRUVARUR",
    email: "rkanna07@gmail.com",
    phone: "7010269970",
    link: "/member/11",
  },
  {
    id: 12,
    name: "Mr. M. GURUKANNAN",
    designation: "ORGANISING SECRETARY",
    company: "GURU LAND PROMOTERS",
    regNo: "TN/L/01/1343",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "THIRUVANNAMALAI",
    email: "tvmgurutravels@gmail.com",
    phone: "9380044447",
    link: "/member/12",
  },
  {
    id: 13,
    name: "Mr. R. GOPINATH",
    designation: "CO-ORDINATOR",
    company: "ADIYA PROPERTIES",
    regNo: "TN/L/01/1174",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "THIRUVANNAMALAI",
    email: "adiyaproperties@gmail.com",
    phone: "9994900222",
    link: "/member/13",
  },
  {
    id: 14,
    name: "Mr. S. K. MUTHU RAMAN",
    designation: "CO-ORDINATOR",
    company: "TRUE VALUE PROPERTIES",
    regNo: "TN/L/01/1366",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "TENKASI",
    email: "tvlp.tamilnadu@gmail.com",
    phone: "9843438000",
    link: "/member/14",
  },
  {
    id: 15,
    name: "Mrs. M. DHARANIKARASI",
    designation: "JOINT SECRETARY",
    company: "SATHYA ELITE PROPERTIES PVT. LTD",
    regNo: "TN/P/01/088",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "CHENNAI",
    email: "sathyapropertybazzar@gmail.com",
    phone: "9962358802",
    link: "/member/15",
  },
  {
    id: 16,
    name: "Mr. R. ESAKIMUTHU",
    designation: "JOINT SECRETARY",
    company: "ARUN LAND PROMOTERS",
    regNo: "TN/L/01/1278",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "THIRUNELVELI",
    email: "resakki@gmail.com",
    phone: "9942658545",
    link: "/member/16",
  },
  {
    id: 17,
    name: "Mr. S. SHANAVAS",
    designation: "DEPUTY SECRETARY",
    company: "GREEN DEVELOPERS",
    regNo: "TN/L/01/1364",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "THIRUVANNAMALAI",
    email: "",
    phone: "9361683419",
    link: "/member/17",
  },
  {
    id: 18,
    name: "Mr. G. R. GANAPATHI",
    designation: "DEPUTY SECRETARY",
    company: "RAMCHAND CITY DEVELOPERS",
    regNo: "TN/P/01/107",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "TIRUCHY",
    email: "ramchanddevlopers@gmail.com",
    phone: "9789166064",
    link: "/member/18",
  },
  {
    id: 19,
    name: "Mr. K. SANKAR",
    designation: "DEPUTY TREASURER",
    company: "SIVAN MALAI DEVELOPERS",
    regNo: "TN/L/01/1392",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "THIRUVANNAMALAI",
    email: "krishnasankar@gmail.com",
    phone: "9994545445",
    link: "/member/19",
  },
  {
    id: 20,
    name: "Mr. M. UMA MAGESH",
    designation: "EXECUTIVE COMMITTEE VICE CHAIRMAN",
    company: "ROYAL LAND PROMOTERS",
    regNo: "TN/L/01/1026",
    category: "LAYOUT OWNERS & PROMOTERS",
    location: "CHENNAI",
    email: "magesh787@gmail.com",
    phone: "9841065498",
    link: "/member/20",
  },

];
export default OwnersData;