const members = [
  {
    id: 1,
    name: "Mr. D. Anebarassou",
    designation: "President",
    company: "Anbu Real Estate",
    regNo: "PY/L/01/1003",
    state: "Pondicherry State",
    location: "Pondicherry",
    email: "anebarassounanbu@gmail.com",
    phone: "9788588141",
  },
  {
    id: 2,
    name: "Mr. Amar Manisekar",
    designation: "Secretary General",
    company: "ABI Land Promoters",
    regNo: "PY/L/01/1008",
    state: "Pondicherry State",
    location: "Pondicherry",
    email: "amarnathveeraraghavar@gmail.com",
    phone: "9443842578",
  },
  {
    id: 3,
    name: "Mr. N. Gobalakirouchenane",
    designation: "Secretary – Admin",
    company: "GRS Groups",
    regNo: "PY/L/01/1002",
    state: "Pondicherry State",
    location: "Pondicherry",
    email: "gobalakirouchenane@gmail.com",
    phone: "9789336323",
  },
  {
    id: 4,
    name: "Mr. R. Suresh Kumar",
    designation: "Secretary – Operation",
    company: "Pazhani Andavar Group's",
    regNo: "PY/L/01/1016",
    state: "Pondicherry State",
    location: "Pondicherry",
    email: "sureshkumar1974@gmail.com",
    phone: "9092149999",
  },
  {
    id: 5,
    name: "Mr. S. Sakthivel",
    designation: "Secretary – Development",
    company: "Sakthimurugan Real Estate",
    regNo: "PY/L/01/1011",
    state: "Pondicherry State",
    location: "Pondicherry",
    email: "sakthivel197417@gmail.com",
    phone: "9080768441",
  },
  {
    id: 6,
    name: "Mr. Muthu Muthalappan",
    designation: "Treasurer",
    company: "Muthu Real Estate",
    regNo: "PY/L/01/1007",
    state: "Pondicherry State",
    location: "Pondicherry",
    email: "muthureal05@gmail.com",
    phone: "8220925092",
  },
  {
    id: 7,
    name: "Mr. C. Muthu Kumaran",
    designation: "Advisory Board – Chairman",
    company: "Sri Annai Groups",
    regNo: "PY/L/01/1017",
    state: "Pondicherry State",
    location: "Pondicherry",
    email: "sriannaikumaran@gmail.com",
    phone: "9842335544",
  },
  {
    id: 8,
    name: "Mr. S. Ananthan",
    designation: "Vice President",
    company: "Thillai Real Estate",
    regNo: "TN/L/01/1151",
    state: "Pondicherry State",
    location: "Pondicherry",
    email: "thillaireal@gmail.com",
    phone: "9688880444",
  },
  {
    id: 9,
    name: "Mr. M. Kandhan",
    designation: "Organising Secretary",
    company: "Sri Varahi Real Groups",
    regNo: "PY/L/01/1018",
    state: "Pondicherry State",
    location: "Pondicherry",
    email: "kandan09@gmail.com",
    phone: "9787936469",
  },
  {
    id: 10,
    name: "Mr. K. Kangaraj",
    designation: "Deputy Secretary",
    company: "Anbu Group's",
    regNo: "",
    state: "Pondicherry State",
    location: "Pondicherry",
    email: "",
    phone: "9585556923",
  },
];

export default members;
