import hendry from "../../../assets/Members/Patron/HENDRY.jpg";
import chandra from "../../../assets/Members/Patron/CHANDRA_SHEKAR.jpg";
import raja from "../../../assets/Members/Patron/RAJA_SEKAR.jpg";
import jaya from "../../../assets/Members/Patron/JAYACHANDRAN.jpg";
import ravanan from "../../../assets/Members/Patron/RAVANAN_G.jpg";
import senthil from "../../../assets/Members/Patron/SENTHILKUMAR.jpg";
import jawahar from "../../../assets/Members/Patron/JAWAHAR.jpg";
import venkat from "../../../assets/Members/Patron/VENKATRAJ.jpg";
import vishwak from "../../../assets/Members/Patron/SELVAM.jpg";
import tamilarasan from "../../../assets/Members/Patron/TAMILARASAN.jpg";
import LURTHRAJ from "../../../assets/Members/Patron/LURTHRAJ.jpg";
import KRISHNAKUMAR from "../../../assets/Members/Patron/KRISHNAKUMAR.jpg";
import MUTHU from "../../../assets/Members/Patron/MUTHU.jpg";
import ASHOK_KUMAR from "../../../assets/Members/Patron/ASHOK_KUMAR.jpg";
import SUDHAKAR from "../../../assets/Members/Patron/SUDHAKAR.jpg";
import JAISANKAR from "../../../assets/Members/Patron/JAISANKAR.jpg";
import BABU from "../../../assets/Members/Patron/BABU.jpg";
import SRINIVASAN from "../../../assets/Members/Patron/SRINIVASAN.jpg";
// export const patronMembers = [
//   {
//     id: "TN/P/01/001",
//     img: hendry,
//     name: "DR. A. HENDRY",
//     designation: "CHAIRMAN-MD",
//     company: "HIGH VALUE HOUSING AND DEVELOPERS PVT LTD.",
//     location: "Chennai",
//   },
//   {
//     id: "TN/P/01/002",
//     img: chandra,
//     name: "Dr. R. CHANDRA SHEKAR",
//     designation: "MD",
//     company: "SIGARAM GROUP",
//     location: "Coimbatore",
//   },
//   {
//     id: "TN/P/01/003",
//     img: raja,
//     name: "Dr. S. RAJA SEKAR",
//     designation: "CHAIRMAN-MD",
//     company: "KING MAKERS",
//     location: "Madurai",
//   },
//   {
//     id: "TN/P/01/004",
//     img: jaya,
//     name: "Rtn. V. JAYACHANDRAN",
//     designation: "MD",
//     company: "MADRAS CITY PROPERTIES .COM",
//     location: "Salem",
//   },
//   {
//     id: "TN/P/01/005",
//     img: ravanan,
//     name: "RAVANAN G",
//     designation: "MD",
//     company: "VOX GROUP",
//     location: "Trichy",
//   },
//   {
//     id: "TN/P/01/006",
//     img: senthil,
//     name: "Ln. S. SENTHIL KUMAR",
//     designation: "MD",
//     company: "ENNILAM BUILDERS PRIVATE LTD",
//     location: "Erode",
//   },
//   {
//     id: "TN/P/01/007",
//     img: jawahar,
//     name: "P. JAWAHAR",
//     designation: "Managing Partner",
//     company: "VASANTHAM PROMOTERS",
//     location: "Tirunelveli",
//   },
//   {
//     id: "TN/P/01/012",
//     img: venkat,
//     name: "V. VENKATRAJ",
//     designation: "MD",
//     company: "VVR SOUTH INDIA PROPERTIES LLP",
//     location: "Vellore",
//   },
//   {
//     id: "TN/P/01/014",
//      img: vishwak,
//     name: "VISHWAK PROPERTIES",
//     designation: "MD",
//     company: "VISHWAK PROPERTIES",
//     location: "Vellore",
//   },
//   {
//     id: "TN/P/01/015",
//     img: tamilarasan,
//     name: "P. TAMILARASAN",
//     designation: "MD",
//     company: "C. M. PROPERTIES",
//     location: "Chennai",
//   },
//   {
//     id: "TN/P/01/016",
//     img: LURTHRAJ,
//     name: "B.LURTHRAJ PREM",
//     designation: "MD",
//     company: "V.L.C.PROMOTERS",
//     location: "Chennai",
//   },
//   {
//     id: "TN/P/01/018",
//     img: KRISHNAKUMAR,
//     name: "RTN.MPHF.T.KRISHNAKUMAR",
//     designation: "MD",
//     company: "SREE KRISHNA REAL ESTATES",
//     location: "Chennai",
//   },
//   {
    
//     id: "TN/P/01/019",
//     img: MUTHU,
//     name: "MUTHU V",
//     designation: "MD",
//     company: "GREEN FUTURE PROPERTIES",
//     location: "Chennai",
//   },
//   {
//     id: "TN/P/01/021",
//     img: ASHOK_KUMAR,
//     name: "I. ASHOK KUMAR",
//     designation: "MD",
//     company: "V.L. PROMOTERS",
//     location: "Chennai",
//   },
//   {
//     id: "TN/P/01/023",
//     img: SUDHAKAR,
//     name: "J. SUDHAKAR",
//     designation: "MD",
//     company: "SATHYAM PROPERTIES",
//     location: "Chennai",
//   },
//   {

//     id: "TN/P/01/024",
//     img: JAISANKAR,
//     name: "S. JAISANKAR",
//     designation: "MD",
//     company: "J.J. PROMOTER & PROPERTY",
//     location: "Chennai",
//   },
//   {
//     id: "TN/P/01/026",
//     img: BABU,
//     name: "E. BABU",
//     designation: "MD",
//     company: "BABU REALTY",
//     location: "Chennai",
//   },
//   {
//     id: "TN/P/01/028",
//     img: SELVAKUMAR,
//     name: "M. SELVAKUMAR",
//     designation: "PROPRIETOR",
//     company: "SKT PROMOTERS",
//     location: "Chennai",
//   },
//   {
//     id: "TN/P/01/015",
//     img: tamilarasan,
//     name: "P. TAMILARASAN",
//     designation: "MD",
//     company: "C. M. PROPERTIES",
//     location: "Chennai",
//   },
//   {
//     id: "TN/P/01/015",
//     img: tamilarasan,
//     name: "P. TAMILARASAN",
//     designation: "MD",
//     company: "C. M. PROPERTIES",
//     location: "Chennai",
//   },
//   {
//     id: "TN/P/01/015",
//     img: tamilarasan,
//     name: "P. TAMILARASAN",
//     designation: "MD",
//     company: "C. M. PROPERTIES",
//     location: "Chennai",
//   },
//   {
//     id: "TN/P/01/015",
//     img: tamilarasan,
//     name: "P. TAMILARASAN",
//     designation: "MD",
//     company: "C. M. PROPERTIES",
//     location: "Chennai",
//   },
//   {
//     id: "TN/P/01/015",
//     img: tamilarasan,
//     name: "P. TAMILARASAN",
//     designation: "MD",
//     company: "C. M. PROPERTIES",
//     location: "Chennai",
//   },
//   {
//     id: "TN/P/01/015",
//     img: tamilarasan,
//     name: "P. TAMILARASAN",
//     designation: "MD",
//     company: "C. M. PROPERTIES",
//     location: "Chennai",
//   },
// ];
 


export const patronMembers = [
  {
    id: "TN/P/01/001",
    img: hendry,
    name: "DR. A. HENDRY",
    designation: "CHAIRMAN-MD",
    company: "HIGH VALUE HOUSING AND DEVELOPERS PVT LTD.",
    location: "Chennai",
    link: "/patron/TN-P-01-001",
  },
  {
    id: "TN/P/01/002",
    img: chandra,
    name: "Dr. R. CHANDRA SHEKAR",
    designation: "MD",
    company: "SIGARAM GROUP",
    location: "Coimbatore",
    link: "https://www.sigaram.net.in/",
  },
  {
    id: "TN/P/01/003",
    img: raja,
    name: "Dr. S. RAJA SEKAR",
    designation: "CHAIRMAN-MD",
    company: "KING MAKERS",
    location: "Madurai",
    link: "https://kingmakersproperties.com/",
  },
  {
    id: "TN/P/01/004",
    img: jaya,
    name: "Rtn. V. JAYACHANDRAN",
    designation: "MD",
    company: "MADRAS CITY PROPERTIES .COM",
    location: "Salem",
    link: "https://madrascityproperties.com/public/saved_resource.php",
  },
  {
    id: "TN/P/01/005",
    img: ravanan,
    name: "RAVANAN G",
    designation: "MD",
    company: "VOX GROUP",
    location: "Trichy",
    link: "http://voxgroup.com/",
  },
 // {
  //   id: "TN/P/01/006",
  //   img: senthil,
  //   name: "Ln. S. SENTHIL KUMAR",
  //   designation: "MD",
  //   company: "ENNILAM BUILDERS PRIVATE LTD",
  //   location: "Erode",
  //   link: "/patron/TN-P-01-006",
  // },
  {
    id: "TN/P/01/007",
    img: jawahar,
    name: "P. JAWAHAR",
    designation: "Managing Partner",
    company: "VASANTHAM PROMOTERS",
    location: "Tirunelveli",
    link: "https://www.srivasanthampromoters.com/",
  },
  // {
  //   id: "TN/P/01/012",
  //   img: venkat,
  //   name: "V. VENKATRAJ",
  //   designation: "MD",
  //   company: "VVR SOUTH INDIA PROPERTIES LLP",
  //   location: "Vellore",
  //   link: "/patron/TN-P-01-012",
  // },
  {
    id: "TN/P/01/014",
    img: vishwak,
    name: "VISHWAK PROPERTIES",
    designation: "MD",
    company: "VISHWAK PROPERTIES",
    location: "Vellore",
    link: "https://vishwakproperties.in/",
  },
  {
    id: "TN/P/01/015",
    img: tamilarasan,
    name: "P. TAMILARASAN",
    designation: "MD",
    company: "C. M. PROPERTIES",
    location: "Chennai",
    link: "https://www.cmproperties.co.in/",
  },
  {
    id: "TN/P/01/016",
    img: LURTHRAJ,
    name: "B. LURTHRAJ PREM",
    designation: "MD",
    company: "V.L.C. PROMOTERS",
    location: "Chennai",
    link: "https://vlcproperties.com/",
  },
  {
    id: "TN/P/01/018",
    img: KRISHNAKUMAR,
    name: "RTN. MPHF. T. KRISHNAKUMAR",
    designation: "MD",
    company: "SREE KRISHNA REAL ESTATES",
    location: "Chennai",
    link: "https://krishna-real-estate-hub.vercel.app/",
  },
  {
    id: "TN/P/01/019",
    img: MUTHU,
    name: "MUTHU V",
    designation: "MD",
    company: "GREEN FUTURE PROPERTIES",
    location: "Chennai",
    link: "http://greenfuture.pk/",
  },
  {
    id: "TN/P/01/021",
    img: ASHOK_KUMAR,
    name: "I. ASHOK KUMAR",
    designation: "MD",
    company: "V.L. PROMOTERS",
    location: "Chennai",
    link: "https://www.vlpromoters.in/",
  },
  {
    id: "TN/P/01/023",
    img: SUDHAKAR,
    name: "J. SUDHAKAR",
    designation: "MD",
    company: "SATHYAM PROPERTIES",
    location: "Chennai",
    link: "/patron/TN-P-01-023",
  },
  {
    id: "TN/P/01/024",
    img: JAISANKAR,
    name: "S. JAISANKAR",
    designation: "MD",
    company: "J.J. PROMOTER & PROPERTY",
    location: "Chennai",
    link: "https://sathyamproperties.in/",
  },
  {
    id: "TN/P/01/026",
    img: BABU,
    name: "E. BABU",
    designation: "MD",
    company: "BABU REALTY",
    location: "Chennai",
    link: "https://baburealty.com/",
  },
  // {
  //   id: "TN/P/01/028",
  //   img: SELVAKUMAR,
  //   name: "M. SELVAKUMAR",
  //   designation: "PROPRIETOR",
  //   company: "SKT PROMOTERS",
  //   location: "Chennai",
  //   link: "https://sktpromoters.com/",
  // },
  {
    id: "TN/P/01/032",
    img: BABU,
    name: "R.SRINIVASAN",
    designation: "PROPRIETOR",
    company: "SUN PROMOTERS",
    location: "Chennai",
    link: "http://sunpromoters.org/",
  },
  {
    id: "TN/P/01/032",
    img: SRINIVASAN,
    name: "R.SRINIVASAN",
    designation: "PROPRIETOR",
    company: "SUN PROMOTERS",
    location: "Chennai",
    link: "http://sunpromoters.org/",
  }
];
